### ISSUE TITLE
Bad error messages when attempting to run invalid libraries in workflow context

### ISSUE THREAD

**Issue by pranaygp** [vercel/workflow#153]
We need to do a better job of capturing and emitting errors for non node compatible packages that get used inside the workflow. For example, `EventTarget` when trying to use the upstash redis client.

improving stacktraces (#151) is also critical to make the experience of debugging these issues better

```
ReferenceError while running "wrun_01K8VGKHAZ0Z96K2QZ1T1K1WD0" workflow:

evalmachine.<anonymous>:26779
var Subscriber = class extends EventTarget {
                 ^

ReferenceError: EventTarget is not defined
    at evalmachine.<anonymous>:26779:18
    at Script.runInContext (node:vm:149:12)
    at runInContext (node:vm:301:6)
    at /Users/pranaygp/github/vercel-support/v0-community-dashboard/.next/dev/server/chunks/0c935_@workflow_core_dist_cdced69a._.js:2226:158
    at /Users/pranaygp/github/vercel-support/v0-community-dashboard/.next/dev/server/chunks/0c935_@workflow_core_dist_cdced69a._.js:200:34
    at NoopContextManager.with (/Users/pranaygp/github/vercel-support/v0-community-dashboard/.next/dev/server/chunks/4b6e4_@opentelemetry_api_build_esm_9cee443b._.js:122:24)
    at ContextAPI.with (/Users/pranaygp/github/vercel-support/v0-community-dashboard/.next/dev/server/chunks/4b6e4_@opentelemetry_api_build_esm_9cee443b._.js:785:54)
    at NoopTracer.startActiveSpan (/Users/pranaygp/github/vercel-support/v0-community-dashboard/.next/dev/server/chunks/4b6e4_@opentelemetry_api_build_esm_9cee443b._.js:1962:31)
    at ProxyTracer.startActiveSpan (/Users/pranaygp/github/vercel-support/v0-community-dashboard/.next/dev/server/chunks/4b6e4_@opentelemetry_api_build_esm_9cee443b._.js:2009:24
)
    at trace (/Users/pranaygp/github/vercel-support/v0-community-dashboard/.next/dev/server/chunks/0c935_@workflow_core_dist_cdced69a._.js:198:19)
 POST /.well-known/workflow/v1/flow 200 in 182ms

```

x-ref thread: https://vercel.slack.com/archives/C09125LC4AX/p1761855473693419

**Comment by asionesjia** [comment]
Hello, @pranaygp @adriandlam , Is there any progress on this issue? I tried countless temporary patches that didn't work.

**Comment by adriandlam** [comment]
> Hello, [@pranaygp](https://github.com/pranaygp) [@adriandlam](https://github.com/adriandlam) , Is there any progress on this issue? I tried countless temporary patches that didn't work.

hey @asionesjia, can you try updating your `workflow` package to the most recent version? I believe it should be fixed now but do let me know if you're running into issues

**Comment by asionesjia** [comment]
I've upgraded to the latest beta version, and the problem persists. When I move the import statement from the beginning of the file to the call location within the function, the error disappears.

Strangely, when I updated to the latest version, a new error appeared. It occurs during the initial phase of build & dev, but instead of interrupting build & dev, it throws a warning. I use `Bun`, `Monorepo`, `Turbopack`, `nextjs 16.0.10`, `workflow 4.0.1-beta.32`. All packages are the latest.

``` bash
Discovering workflow directives 1226ms
Created steps bundle 11ms
Created intermediate workflow bundle 4ms
Creating webhook route
   ▲ Next.js 16.0.10 (Turbopack, Cache Components)

Creating an optimized production build... 
ERROR failed to read input source map: failed to find input source map file "stdlib.js.map" in "node_modules/.bun/workflow@4.0.1-beta.32+649ea1d4af81ebbd/node_modules/workflow/dist/stdlib.js" file as either "node_modules/.bun/workflow@4.0.1-beta.32+649ea1d4af81ebbd/node_modules/workflow/dist/stdlib.js.map" or with appended .map 
at crates/swc/src/lib.rs:398 

ERROR failed to read input source map: failed to find input source map file "stdlib.js.map" in "node_modules/.bun/workflow@4.0.1-beta.32+649ea1d4af81ebbd/node_modules/workflow/dist/stdlib.js" file as either "node_modules/.bun/workflow@4.0.1-beta.32+649ea1d4af81ebbd/node_modules/workflow/dist/stdlib.js.map" or with appended .map 
at crates/swc/src/lib.rs:398
```

**Comment by adriandlam** [comment]
okay interesting, could you share a minimum repro?

**Comment by dominiksipowicz** [comment]
same/similar issue: https://github.com/vercel/workflow/issues/1161
